name: 'Generate Blog'
on:
  workflow_dispatch:
  issues:
    types: [ opened, edited ]
  issue_comment:
    types: [ created, edited ]
concurrency:
  # just run one action at a time
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #  Check out the repository, so it can read the files it and do other operations
      - name: Generate README
        uses: bxb100/issueblog@v1 # Prefer to use the latest version
        with:
          # Define the README.md header content
          md_header: "## GitLog\nMy personal blog using issues and GitHub Actions\n[RSS Feed](https://bxb100.github.io/blog/feed.xml)"
